<?php require_once("../includes/header.php");?>
    <body>
        <!-- navbar -->
        <div class="navbar">
            <nav class="nav__mobile"></nav>
            <div class="container">
                <div class="navbar__inner">
                    <a href="index.html" class="navbar__logo">Sitename <small>(unlimited)</small></a>
                    <nav class="navbar__menu">
                        <ul>
                            <li><a href="../">Home</a></li>
                            <li><a href="../about/">About Us</a></li>
                            <li><a href="../faq/">FAQs</a></li>
                            <li><a href="../terms/">Terms</a></li>
                            <li><a href="../privacy/">Privacy Policy</a></li>
                            <li><a href="../login/">Log In</a></li>
                            <li><a href="../signup/">Sign Up</a></li>
                        </ul>
                    </nav>
                    <div class="navbar__menu-mob"><a href="#" id='toggle'><svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" class=""></path></svg></a></div>
                </div>
            </div>
        </div>
            <!-- Hero unit -->
        <div class="page__header">
            <div class="hero__overlay hero__overlay--gradient"></div>
            <div class="hero__mask"></div>
            <div class="page__header__inner">
                <div class="container">
                    <div class="page__header__content">
                        <div class="page__header__content__inner" id='navConverter'>
                            <h1 class="page__header__title">Privacy Policy</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page content -->
        <div class="app">
            <div class="container">
                <div class="text-container">
                    <p>Effective date: August 29, 2018</p>
                    <p>Spincash ("us", "we", or "our") operates the http://spincash.net website (hereinafter referred to as the "Service").</p>
                    <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. This Privacy Policy for Spincash is generated by the Privacy Policy Generator from TermsFeed.</p>
                    <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from http://spincash.net :</p>
                    
                    <h2>Definitions</h2>
    
                    <p><strong>Service</strong><br>
                        Service is the http://spincash.net website operated by Spincash
                    </p>	
    
                    <p><strong>Personal Data</strong><br>
                        Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    </p>
    
                    <p><strong>Usage Data</strong><br>
                        Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </p>
    
                    <p><strong>Cookies</strong><br>
                        Cookies are small files stored on your device (computer or mobile device).
                    </p>    
                    
                    <h1>Information Collection and Use</h1>
                    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                    <hr>
                    
                    <h2>Types of Data Collected</h2>
                    <p><strong>Personal Data</strong><br>
                        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                        <br>> Email address
                        <br>> Phone number
                        <br>> Cookies and Usage Data
                    </p>
                       
                    <p><strong>Usage Data</strong><br>
                        <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>

                        <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
                        
                        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                        
                        <p>Examples of Cookies we use:</p>
                        
                        > Session Cookies. We use Session Cookies to operate our Service.
                        <br>> Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
                        <br>> Security Cookies. We use Security Cookies for security purposes.
                    </p>
    
                    <h2>Registration</h2>
                                       
                    <p><strong>Can Free member invite new member?</strong><br>
                    Yes. Free members can invite new members with the referreal link that will be provided in the dashboard</p>
    
                    <p><strong>Can I use the same email for multiple accounts?</strong><br>
                    No. Each account need to use different username, and also different email addresses.</p>
    
                    <p><strong>Do I need to provide real email address?</strong><br>
                    Yes. All notifications, reminder and account recovery need a valid email address.</p>
                    <p>You need a valid email address to update your profile. If you registered with fake/wrong email address, the account is not accessible and will expire.</p>
    
                    <p><strong>Do I need to provide real phone number?</strong><br>
                    This is optional. Members feel more confident if they can contact you to ask about the program and donation process.
                    </p>
    
                    <p><strong>I did not receive any email from sitename after registration.</strong><br>
                    It could be in your Spam/Junk box. And it is also possible the email address is not valid. You can try 'Forgot Password' in login page.</p>
  
                    <h2>Bank &amp; Payment Methods</h2>
    
                    <p><strong>Why do I need to provide bank details?</strong><br>
                    Your donators will make donation directly to your bank account.</p>
                        
                    <p><strong>How many bank accounts can I enter?</strong><br>
                    Every member can add up to 5 bank accounts.</p>
                        
                    <p><strong>Can I use the same bank account for multiple account?</strong><br>
                    Yes. If you have more than 1 sitename account or you help to manage your friend/family account, you can use the same bank account information for all of the accounts.</p>
                        
                    <p><strong>Can I edit, add, remove payment method?</strong><br>
                    Yes you can do so at anytime. But please make sure you have at least 1 payment method available, or else your donator wont be able to donate to you.</p>
    
                    <h2>Miscellaneous</h2>
    
                    <p><strong>Hashtag for sitename?</strong><br>
                    The official hashtag for sitename  is <b>#sitename</b></p>
                    <p>This hashtag is used to gather all marketing effort and materials to be as reference for every member. It is encouraged to all members to include #sitename in all marketing.</p>
    
                    <p><strong>Is refund available?</strong><br>
                    No refund is available after donation is made. Donation is from a member to another member, it is not managed or held by the system or 3rd party.</p>
                    
                    <p><strong>How I can start inviting donators?</strong><br>
                    The easiest way is you can start promoting your own referral link to social network site like Facebook, Twitter and chat application like Whatsapp, Telegram, Wechat etc.</p>
                    <p>If your referrer is active and activate spillover feature, you can get new members from your referrer's extra referrals.</p>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <div class="footer footer--dark">
            <div class="container">
                <div class="footer__inner">
                    <a href="index.html" class="footer__textLogo">Sitename.</a>
                    <div class="footer__data">
                        <div class="footer__data__item">
                        </div>
                        <div class="footer__data__item">
                        </div>
                        <div class="footer__data__item">
                            <div class="footer__row">
                                <a href="../login" class="footer__link">Log In</a> - 
                                <a href="../signup" class="footer__link">Sign Up</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src='../themes/front/js/app.min.js'></script>
        <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','../www.google-analytics.com/analytics.js','ga');ga('create', 'UA-70494693-1', 'auto');ga('send', 'pageview');</script>
    </body>
</html>